image_logger:
  _target_: src.logger.ImageLogger
  batch_frequency: 500
  dirpath: ${paths.output_dir}/images/
  save_separate: false
  dpi: 350
  save_recon: false
  diffusion_steps: 50
  save_latent: false

weights_checkpoint_step:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/weights/
  every_n_train_steps: 5000
  save_weights_only: true
  save_top_k: -1

weights_checkpoint_epoch:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/weights_epoch/
  every_n_epochs: 1
  mode: max # to differ the state_key 
  save_weights_only: true
  save_top_k: -1

state_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints/
  every_n_epochs: 1
  # every_n_train_steps: 100
