_target_: pytorch_lightning.trainer.Trainer

# accumulate_grad_batches: 1

max_epochs: 3
# max_steps: -1

strategy: ddp

accelerator: gpu
devices: -1

# mixed precision for extra speed-up
precision: 16 # bf16, 32, 
